### ISSUE TITLE
Add me as a collaborator?

### ISSUE THREAD

**Issue by Wikiemol** [116point2/9APR-SHOW#2]
@116point2 
To do so, go to settings (should be next to Graphs), then Collaborators, then type in my username at the bottom, and click "Add Collaborator".

**Comment by Wikiemol** [comment]
Btw you can use

## Markdown

for these comments.

This has the advantage of the comments being:
- Sleek
- Sexy
- Delightful to use

:+1:

**Comment by 116point2** [comment]
## Boops 
- boops
- boople
